#!/usr/bin/env bash
#
# mayhem/test.sh — the functional oracle for the Bottlerocket Mayhem integration. RUNS what
# mayhem/build.sh built; compiles nothing. Two layers, BOTH behavioral:
#
#   1. Known-answer probes (UNCONDITIONAL — a missing probe/fixture is a FAILURE, never a
#      skip): /mayhem/bottlerocket-kat (mayhem/kat, CLEAN + dynamically linked) exercises the
#      exact code the fuzz targets cover — parse-datetime (target `parse`) and ghostdog's GPT
#      device-type scan over gptman (target `img-scanning`) — on fixed inputs, and every
#      output line is compared against an exact expected string derived independently of the
#      program (Python datetime epochs; GPT images from mayhem/img-scanning/mkseeds.py). A
#      neutered / exit(0) program prints nothing and fails here — bash and coreutils do the
#      comparison, where sabotage cannot hide.
#   2. Bottlerocket's OWN assertion suite: the sources/ workspace unit + doc tests
#      (datastore, models, migration-helpers, retry-read, settings-migrations, ...),
#      precompiled by build.sh with NORMAL flags; counts parsed from libtest's own
#      "test result:" summary lines, with "no results parsed" a hard failure.
#
# Emits a CTRF summary (${CTRF_REPORT:-$SRC/ctrf-report.json}) + a compact `CTRF {...}`
# stdout line; exit 0 iff failed == 0.
set -uo pipefail
[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH
: "${MAYHEM_JOBS:=$(nproc)}"   # build parallelism knob (unused here: nothing is compiled)
RUST_CHANNEL="${RUST_CHANNEL:-$(rustup show active-toolchain 2>/dev/null | awk '{print $1}')}"
cd "$SRC"

# emit_ctrf <tool> <passed> <failed> [skipped] [pending] [other]
# Writes a CTRF report (file + stdout `CTRF {...}` marker) and returns non-zero iff failed>0.
emit_ctrf() {
  local tool="$1" passed="$2" failed="$3" skipped="${4:-0}" pending="${5:-0}" other="${6:-0}"
  local tests=$(( passed + failed + skipped + pending + other ))
  cat > "${CTRF_REPORT:-$SRC/ctrf-report.json}" <<JSON
{
  "results": {
    "tool": { "name": "$tool" },
    "summary": {
      "tests": $tests,
      "passed": $passed,
      "failed": $failed,
      "pending": $pending,
      "skipped": $skipped,
      "other": $other
    }
  }
}
JSON
  printf 'CTRF {"results":{"tool":{"name":"%s"},"summary":{"tests":%d,"passed":%d,"failed":%d,"pending":%d,"skipped":%d,"other":%d}}}\n' \
    "$tool" "$tests" "$passed" "$failed" "$pending" "$skipped" "$other"
  [ "$failed" -eq 0 ]
}

KAT_PASS=0
KAT_FAIL=0

# ── Layer 1: known-answer probes (UNCONDITIONAL) ────────────────────────────────────────────
KAT_BIN="/mayhem/bottlerocket-kat"
SEED_DIR="mayhem/img-scanning/testsuite"     # committed fixtures the GPT probes read
KAT_OUT="$("$KAT_BIN" "$SEED_DIR" 2>&1)" || KAT_OUT="${KAT_OUT:-<probe did not run>}"
echo "--- KAT probe output ($KAT_BIN $SEED_DIR) ---"
echo "$KAT_OUT"
kat_expect() { # kat_expect <exact line>
  if printf '%s\n' "$KAT_OUT" | grep -qxF -- "$1"; then
    echo "KAT OK: $1"; KAT_PASS=$((KAT_PASS+1))
  else
    echo "KAT FAIL: expected exact line: $1" >&2; KAT_FAIL=$((KAT_FAIL+1))
  fi
}
# parse-datetime (fuzz target `parse`). Expected epochs computed with Python's datetime.
kat_expect 'KAT1 rfc3339_utc_epoch=1609459200'
kat_expect 'KAT2 rfc3339_tz_epoch=1582972496'
kat_expect 'KAT3 rfc3339_frac_epoch=1686843000 nanos=123456789'
kat_expect 'KAT4 offsets=3600,604800,1209600,0,302400000'
kat_expect "KAT5 err=Date argument 'in 1 month' is invalid: date argument's unit must be hours/days/weeks"
kat_expect "KAT6 err=Date argument had count '99999999999 hours' that failed to parse as integer: number too large to fit in target type"
kat_expect 'KAT7 rejected=err,err,err,err'
# ghostdog device-type scan over gptman (fuzz target `img-scanning`). Images generated by
# mayhem/img-scanning/mkseeds.py: 16 x 512 B sectors (first usable LBA 3, last 13, 4 entries)
# and 6 x 4096 B sectors (backup header at LBA 5).
kat_expect 'KAT8 zeros=ephemeral'
kat_expect 'KAT9 gpt512-bottlerocket-root.img=system'
kat_expect 'KAT9 gpt512-bottlerocket-name.img=system'
kat_expect 'KAT9 gpt512-linux-data.img=ephemeral'
kat_expect 'KAT9 gpt512-efi-linux.img=system'
kat_expect 'KAT9 gpt4k-bottlerocket-root.img=system'
kat_expect 'KAT9 mbr-only-4k.img=ephemeral'
kat_expect 'KAT10 sector_size=512 first_usable_lba=3 last_usable_lba=13 entries=4 used=[1, 2] name1=BOTTLEROCKET-ROOT-A name2=BOTTLEROCKET-DATA range1=3..=6'
kat_expect 'KAT11 sector_size=4096 backup_lba=5 name1=BOTTLEROCKET-ROOT-B'
echo "KAT summary: passed=$KAT_PASS failed=$KAT_FAIL"

# ── Layer 2: Bottlerocket's own suite (sources/ workspace, prebuilt by build.sh) ────────────
LOG="$(mktemp)"
env -u RUSTFLAGS -u CFLAGS -u CXXFLAGS \
  cargo +"$RUST_CHANNEL" test --offline --no-fail-fast --manifest-path sources/Cargo.toml --workspace 2>&1 | tee "$LOG"
rc=${PIPESTATUS[0]}

# libtest summary lines: "test result: ok. N passed; M failed; K ignored; ..."
read -r P F S < <(awk '/^test result:/ {p+=$4; f+=$6; s+=$8} END {print p+0, f+0, s+0}' "$LOG")
rm -f "$LOG"
echo "cargo test summary: passed=$P failed=$F ignored=$S (exit=$rc)"

if [ "$((P + F + S))" -eq 0 ]; then
  echo "ERROR: no 'test result:' lines found — suite did not run (build.sh should have prebuilt it)" >&2
  F=$((F + 1))
elif [ "$rc" -ne 0 ] && [ "$F" -eq 0 ]; then
  echo "ERROR: cargo test exited $rc without reporting failures (harness error)" >&2
  F=$((F + 1))
fi

emit_ctrf "bottlerocket-kat+cargo-test" "$((P + KAT_PASS))" "$((F + KAT_FAIL))" "$S"
